### PR TITLE
data update: opentargets, intact

### PR DESCRIPTION
**Pull request by DSuveges**
**Data updates**:

* Uniprot covid url update
* OpenTargets data update to 20.09
* Moving to the new Intact release for human interactions and covid complexes. (links now contain the data version)

**Changes in the result summary**:

* Slightly higher number of targets
* Increased numbers for all covid related fields

### CODE REVIEW

**Comment by AsierGonzalez** [comment]
I had issues running it on Ubuntu 20.04 LTS due to problems with Ensembl SSL certificates as described [here](https://github.com/Ensembl/ensembl-rest/issues/427). The way I solved it was adding `verify=False` to the get request on [row 15 of `uniprot_parser.py`](https://github.com/opentargets/ot_covid19/blob/04714b58fa3cd6b42e63c8306ff1a0ba502ce8ac/src/parsers/uniprot_parser.py#L15):

`response = requests.get(URL, verify=False).json()`

Should we add this to the code so that it works for anyone running it on Ubuntu 20.04 LTS or should we find a different solution, or add it to the README? Hopefully Ensembl or OpenSSL will fix the issue at their end soon and this will not be needed.

**Comment by DSuveges** [comment]
Not sure... maybe we should just use an other downloadable file and circumvent the API usage. But it certainly less laborious.

**Comment by AsierGonzalez** [comment]
That is a good point. I have checked the Ensembl JSON file and I think that we could use the `Uniprot/SWISSPROT` or the `xrefs` fields to do the mapping. See example below for protein `ENSG00000184012 - TMPRSS2` which should be the mapping for `O15393`:
```
"Uniprot/SWISSPROT":
[
  "O15393"
],
"xrefs":
[
  {
    "display_id": "LRG_1368",
    "primary_id": "LRG_1368",
    "db_display": "LRG display in Ensembl gene",
    "info_type": "DIRECT",
    "info_text": "",
    "description": "Locus Reference Genomic record for TMPRSS2",
    "dbname": "ENS_LRG_gene"
  },
  {
    "display_id": "ENSG00000184012",
    "primary_id": "ENSG00000184012",
    "db_display": "Expression Atlas",
    "info_type": "DIRECT",
    "info_text": "",
    "dbname": "ArrayExpress"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "7113",
    "db_display": "NCBI gene (formerly Entrezgene)",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "transmembrane serine protease 2",
    "dbname": "EntrezGene"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "HGNC:11876",
    "db_display": "HGNC Symbol",
    "description": "transmembrane serine protease 2",
    "dbname": "HGNC",
    "synonyms": [
      "PRSS10"
    ],
    "info_type": "DIRECT",
    "info_text": "Generated via ensembl_manual"
  },
  {
    "display_id": "TRANSMEMBRANE PROTEASE, SERINE 2; TMPRSS2TMPRSS2/ERG FUSION GENE, INCLUDED [*602060]",
    "primary_id": "602060",
    "db_display": "MIM gene",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "TRANSMEMBRANE PROTEASE, SERINE 2; TMPRSS2TMPRSS2/ERG FUSION GENE, INCLUDED;;TMPRSS2/ETV1 FUSION GENE, INCLUDED",
    "dbname": "MIM_GENE"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "O15393",
    "db_display": "UniProtKB Gene Name",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "",
    "dbname": "Uniprot_gn"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "C9J5Y1",
    "db_display": "UniProtKB Gene Name",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "",
    "dbname": "Uniprot_gn"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "C9JKZ3",
    "db_display": "UniProtKB Gene Name",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "",
    "dbname": "Uniprot_gn"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "C9JB05",
    "db_display": "UniProtKB Gene Name",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "",
    "dbname": "Uniprot_gn"
  },
  {
    "display_id": "TMPRSS2",
    "primary_id": "7113",
    "db_display": "WikiGene",
    "info_type": "DEPENDENT",
    "info_text": "",
    "description": "transmembrane serine protease 2",
    "dbname": "WikiGene"
  }
]
```

**Comment by DSuveges** [comment]
No, I'm afraid it's not that easy... I think you need to look up the non human viral proteins anyway, they are not in the file. I have added your fix to the code and it runs for me as well. We can leave as it is for now and later decide to refactor.

**Comment by AsierGonzalez** [comment]
Sounds good, let's merge then.

**Review by AsierGonzalez — APPROVED** [review]

**Pull request merged**
